### ISSUE TITLE
An error answer got from testing Triangle Counting

### ISSUE THREAD

**Issue by IslandGod** [narayanan2004/GraphMat#22]
Hello,
When I ran the below cmd to test Triangle Counting in GraphMat:

> ./bin/TriangleCounting ../data/soc-LiveJournal1.mtx

I've got the below output:

> Reading file: ../data/soc-LiveJournal1.mtx0
> Could not open file: ../data/soc-LiveJournal1.mtx1
> Got: 4847571 by 4847571  vertices
> Got: 68993773 edges
> Rank 0: Before shuffle 68993773 edges
> Rank 0: After shuffle 68993773 edges
> Rank 0: Before shuffle 68993773 edges
> Rank 0: After shuffle 68993773 edges
> Finished GraphMat read + construction, time: 5.78043
> Completed 1 iterations 
> Time = 3011.534 ms 
> Total triangles = 0 
> 1 : 0 : 
> 2 : 0 : 
> 3 : 0 : 
> 4 : 0 : 
> 5 : 0 : 
> 6 : 0 : 
> 7 : 0 : 
> 8 : 0 : 
> 9 : 0 : 
> 10 : 0 : 

It seems like an error answer. And I do not know the reason.
Please give me some help. Any info will help.

Thank you!

**Comment by narayanan2004** [comment]
The default version of triangle counting assumes a dag. You can try converting your text graph to a binary format dag using the graph_converter tool 
`bin/graph_converter --uppertriangular 1 --inputformat 1 --outputformat 0 --inputheader 0 --outputheader 1 --nvertices < nvertices > < input text file prefix> < output graphmat file prefix>`. 
Refer to examples in [https://github.com/narayanan2004/GraphMat/wiki/Reading-graph-files](https://github.com/narayanan2004/GraphMat/wiki/Reading-graph-files) if you would rather do the transformation in the code itself. Please let me know if the problem still persists.

**Comment by IslandGod** [comment]
Thank you for fast reply. 
I ran the cmd using a mtx file which has no header:
```
sudo mpirun -np 1 bin/graph_converter --uppertriangular 1 --inputformat 1 --outputformat 0 --inputheader 0 --outputheader 1 --nvertices 4847571 ../../data/soc-LiveJournal0.mtx soc-LiveJournal0.bin
&& ./bin/TriangleCounting soc-LiveJournal0.bin
```

But I still got the wrong answer:
```
Reading file: soc-LiveJournal0.bin0
Could not open file: soc-LiveJournal0.bin1
Got: 4847571 by 4847571  vertices
Got: 42851237 edges
Rank 0: Before shuffle 42851237 edges
Rank 0: After shuffle 42851237 edges
num partitions: 384
set_edge_pointers time: 0.564774
Allocating nnz vals: 42851237
fn time: 1.56434
Rank 0: Before shuffle 42851237 edges
Rank 0: After shuffle 42851237 edges
num partitions: 384
set_edge_pointers time: 0.585779
Allocating nnz vals: 42851237
fn time: 1.41217
Finished GraphMat read + construction, time: 5.23209
Completed 1 iterations 
Completed 1 iterations 
Time = 1254.295 ms 
Total triangles = 0 
1 : 0 : 
2 : 0 : 
3 : 0 : 
4 : 0 : 
5 : 0 : 
6 : 0 : 
7 : 0 : 
8 : 0 : 
9 : 0 : 
10 : 0 : 
```

I do not know the reason causing this problem. Please give me some help.

**Comment by narayanan2004** [comment]
Can you show (say) the first 10 lines of the graph text file?

**Comment by IslandGod** [comment]
This dataset is soc-LiveJournal, which has 4847571 vertices and 68993773 edges. The first 10 lines is as below:

> 1 2 1
> 1 3 1
> 1 4 1
> 1 5 1
> 1 6 1
> 1 7 1
> 1 8 1
> 1 9 1
> 1 10 1
> 
>

**Comment by narayanan2004** [comment]
I tried running the latest version of GraphMat on the livejournal graph and I get the right answer as below. Can you please make sure you are running the latest version of the code in the master branch? 
I made a typo in the command to convert to uppertriangular; you only need to put `--uppertriangular` not `--uppertriangular 1`. 

> Reading file: soc-lj.ut.bin.mtx0
Could not open file: soc-lj.ut.bin.mtx1
Got: 4847571 by 4847571  vertices
Got: 42851237 edges
Rank 0: Before shuffle 42851237 edges
Rank 0: After shuffle 42851237 edges
num partitions: 1408
set_edge_pointers time: 0.746896
Allocating nnz vals: 42851237
fn time: 1.06978
Rank 0: Before shuffle 42851237 edges
Rank 0: After shuffle 42851237 edges
num partitions: 1408
set_edge_pointers time: 0.557166
Allocating nnz vals: 42851237
fn time: 0.816187
Finished GraphMat read + construction, time: 3.35581
Completed 1 iterations
Completed 1 iterations
Time = 936.622 ms
Total triangles = 285730264
1 : 0 :
2 : 2 :
3 : 0 :
4 : 3 :
5 : 9 :
6 : 64 :
7 : 1 :
8 : 0 :
9 : 6 :
10 : 0 :

**Comment by narayanan2004** [comment]
@IslandGod Has this issue been resolved for you?

**Comment by IslandGod** [comment]
I have solved this problem by your approach. Thank you so much!

**Comment by IslandGod** [comment]
Yes, I have solved the problem by your approach. Thank you so much!




| |
yang
邮箱：18976522633@163.com
|

签名由 网易邮箱大师 定制

On 03/08/2018 08:02, Narayanan wrote:

@IslandGod Has this issue been resolved for you?
